using Mro.Domain.Aggregates.Employee.Enums;
using Mro.Domain.Entities;

namespace Mro.Domain.Aggregates.Employee;

/// <summary>
/// A document attached to an employee record (scanned licence, training cert, authorisation letter, etc.).
///
/// Files are stored in blob storage; this entity stores only the metadata and storage path.
/// Access to the file is mediated through pre-signed download URLs generated by IDocumentStorageService.
/// </summary>
public sealed class EmployeeAttachment : AuditableEntity
{
    public Guid EmployeeId { get; private set; }

    public AttachmentType AttachmentType { get; private set; }

    /// <summary>Human-readable name shown in the UI (e.g. "Part-66 Licence B1.1 – 2024 scan").</summary>
    public string DisplayName { get; private set; } = string.Empty;

    /// <summary>Blob storage path (e.g. "employee-attachments/{orgId}/{empId}/{attachmentId}.pdf").</summary>
    public string StoragePath { get; private set; } = string.Empty;

    public long FileSizeBytes { get; private set; }

    /// <summary>MIME type reported by the client at upload time (e.g. "application/pdf", "image/jpeg").</summary>
    public string ContentType { get; private set; } = string.Empty;

    /// <summary>
    /// Optional link to a specific Licence.Id or TrainingRecord.Id that this file documents.
    /// Null for general employee documents.
    /// </summary>
    public Guid? LinkedEntityId { get; private set; }

    // EF Core
    private EmployeeAttachment() { }

    internal static EmployeeAttachment Create(
        Guid employeeId,
        AttachmentType attachmentType,
        string displayName,
        string storagePath,
        long fileSizeBytes,
        string contentType,
        Guid organisationId,
        Guid actorId,
        Guid? linkedEntityId = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(displayName);
        ArgumentException.ThrowIfNullOrWhiteSpace(storagePath);
        ArgumentException.ThrowIfNullOrWhiteSpace(contentType);

        return new EmployeeAttachment
        {
            EmployeeId     = employeeId,
            AttachmentType = attachmentType,
            DisplayName    = displayName.Trim(),
            StoragePath    = storagePath.Trim(),
            FileSizeBytes  = fileSizeBytes,
            ContentType    = contentType.Trim(),
            LinkedEntityId = linkedEntityId,
            OrganisationId = organisationId,
            CreatedBy      = actorId,
            UpdatedBy      = actorId,
            CreatedAt      = DateTimeOffset.UtcNow,
            UpdatedAt      = DateTimeOffset.UtcNow,
        };
    }

    internal void SoftDelete(Guid actorId)
    {
        DeletedAt = DateTimeOffset.UtcNow;
        DeletedBy = actorId;
        UpdatedAt = DateTimeOffset.UtcNow;
        UpdatedBy = actorId;
    }
}
