using Mro.Domain.Aggregates.Defect.Enums;
using Mro.Domain.Aggregates.Defect.Events;
using Mro.Domain.Application;
using Mro.Domain.Common.Audit;
using Mro.Domain.Entities;

namespace Mro.Domain.Aggregates.Defect;

/// <summary>
/// Aggregate root for a maintenance defect (snag, discrepancy, finding).
///
/// Invariants:
///   - DefectNumber is unique per organisation (generated by the application layer).
///   - A defect may not be deferred if it already has an active deferral.
///   - AD-mandated defects (IsAdMandated = true) cannot be Closed without Clearing first (HS-008).
///   - Clearing requires a CRS action to have been recorded against the defect.
///   - Deferral must not exceed the MEL category maximum period.
///
/// State machine:
///   Reported → Triaged → Open
///   Open → Deferred (one active deferral at a time)
///   Deferred → Open (deferral revoked/expired — re-evaluation required)
///   Deferred → RectificationInProgress
///   Open | Deferred | RectificationInProgress → InspectionPending (after rectification logged)
///   InspectionPending → Cleared (after CRS action recorded by authorised staff)
///   Cleared → Closed
///   Open | Deferred | RectificationInProgress | InspectionPending → Closed (no-fault-found / admin)
/// </summary>
public sealed class Defect : AuditableEntity
{
    /// <summary>
    /// System-generated defect reference number (e.g. "DEF-2025-00042").
    /// Unique within the organisation.
    /// </summary>
    public string DefectNumber { get; private set; } = string.Empty;

    /// <summary>Aircraft this defect was recorded against.</summary>
    public Guid AircraftId { get; private set; }

    public DefectStatus Status { get; private set; } = DefectStatus.Reported;

    public DefectSeverity Severity { get; private set; }

    public DefectSource Source { get; private set; }

    /// <summary>ATA chapter/section where the defect is located (e.g. "27-51").</summary>
    public string AtaChapter { get; private set; } = string.Empty;

    /// <summary>Human-readable description of the defect.</summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>
    /// Station (airport) at which the defect was discovered.
    /// Cross-module FK — plain Guid, no navigation.
    /// </summary>
    public Guid? DiscoveredAtStationId { get; private set; }

    /// <summary>UTC timestamp the defect was physically observed (may precede report creation).</summary>
    public DateTimeOffset DiscoveredAt { get; private set; }

    /// <summary>
    /// Set when this defect is mandated by an Airworthiness Directive.
    /// AD-mandated defects have stricter closure rules (HS-008).
    /// </summary>
    public bool IsAdMandated { get; private set; }

    /// <summary>If IsAdMandated, the AD document ID that mandates rectification.</summary>
    public Guid? AdDocumentId { get; private set; }

    /// <summary>User assigned as the responsible engineer for rectification planning.</summary>
    public Guid? AssignedToUserId { get; private set; }

    /// <summary>
    /// Work Order ID this defect is being rectified under.
    /// Cross-module FK — plain Guid, no navigation.
    /// </summary>
    public Guid? WorkOrderId { get; private set; }

    /// <summary>Reason provided when closing without rectification.</summary>
    public string? ClosureReason { get; private set; }

    private readonly List<DefectAction> _actions = [];
    private readonly List<DeferredDefect> _deferrals = [];

    public IReadOnlyCollection<DefectAction> Actions => _actions.AsReadOnly();
    public IReadOnlyCollection<DeferredDefect> Deferrals => _deferrals.AsReadOnly();

    public DeferredDefect? ActiveDeferral =>
        _deferrals.FirstOrDefault(d => d.IsActive && !d.IsExpired);

    // EF Core
    private Defect() { }

    // ── State machine ────────────────────────────────────────────────────────

    private static readonly IReadOnlyDictionary<DefectStatus, IReadOnlySet<DefectStatus>> AllowedTransitions =
        new Dictionary<DefectStatus, IReadOnlySet<DefectStatus>>
        {
            [DefectStatus.Reported]               = new HashSet<DefectStatus> { DefectStatus.Triaged },
            [DefectStatus.Triaged]                = new HashSet<DefectStatus> { DefectStatus.Open },
            [DefectStatus.Open]                   = new HashSet<DefectStatus> { DefectStatus.Deferred, DefectStatus.RectificationInProgress, DefectStatus.Closed },
            [DefectStatus.Deferred]               = new HashSet<DefectStatus> { DefectStatus.Open, DefectStatus.RectificationInProgress, DefectStatus.Closed },
            [DefectStatus.RectificationInProgress]= new HashSet<DefectStatus> { DefectStatus.InspectionPending, DefectStatus.Closed },
            [DefectStatus.InspectionPending]      = new HashSet<DefectStatus> { DefectStatus.Cleared, DefectStatus.Closed },
            [DefectStatus.Cleared]                = new HashSet<DefectStatus> { DefectStatus.Closed },
            [DefectStatus.Closed]                 = new HashSet<DefectStatus>(),
        };

    private DomainResult SetStatus(DefectStatus newStatus, Guid actorId, string description)
    {
        if (!AllowedTransitions[Status].Contains(newStatus))
            return DomainResult.Failure(
                $"Transition from '{Status}' to '{newStatus}' is not permitted.");

        var from = Status;
        Status = newStatus;
        UpdatedBy = actorId;
        UpdatedAt = DateTimeOffset.UtcNow;

        RaiseDomainEvent(new DefectStatusChangedEvent
        {
            ActorId = actorId,
            OrganisationId = OrganisationId,
            EntityType = nameof(Defect),
            EntityId = Id,
            EventType = ComplianceEventType.RecordUpdated,
            DefectNumber = DefectNumber,
            FromStatus = from,
            ToStatus = newStatus,
            Description = description,
        });

        return DomainResult.Ok();
    }

    // ── Factory ──────────────────────────────────────────────────────────────

    public static Defect Raise(
        string defectNumber,
        Guid aircraftId,
        DefectSeverity severity,
        DefectSource source,
        string ataChapter,
        string description,
        DateTimeOffset discoveredAt,
        Guid organisationId,
        Guid actorId,
        Guid? discoveredAtStationId = null,
        bool isAdMandated = false,
        Guid? adDocumentId = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(defectNumber);
        ArgumentException.ThrowIfNullOrWhiteSpace(ataChapter);
        ArgumentException.ThrowIfNullOrWhiteSpace(description);

        if (isAdMandated && adDocumentId is null)
            throw new ArgumentException(
                "AD document ID must be provided for AD-mandated defects.", nameof(adDocumentId));

        var defect = new Defect
        {
            DefectNumber = defectNumber.Trim().ToUpperInvariant(),
            AircraftId = aircraftId,
            Severity = severity,
            Source = source,
            AtaChapter = ataChapter.Trim(),
            Description = description.Trim(),
            DiscoveredAt = discoveredAt,
            DiscoveredAtStationId = discoveredAtStationId,
            IsAdMandated = isAdMandated,
            AdDocumentId = adDocumentId,
            OrganisationId = organisationId,
            CreatedBy = actorId,
            UpdatedBy = actorId,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
        };

        defect.RaiseDomainEvent(new DefectRaisedEvent
        {
            ActorId = actorId,
            OrganisationId = organisationId,
            EntityType = nameof(Defect),
            EntityId = defect.Id,
            EventType = ComplianceEventType.DefectRaised,
            DefectNumber = defect.DefectNumber,
            AircraftId = aircraftId,
            Severity = severity,
            Source = source,
            Description = $"Defect '{defect.DefectNumber}' raised on aircraft {aircraftId} ({severity}, ATA {ataChapter}): {description}",
        });

        return defect;
    }

    // ── Workflow transitions ──────────────────────────────────────────────────

    /// <summary>Engineer reviews the report, sets priority and assignee.</summary>
    public DomainResult Triage(Guid assignedToUserId, DefectSeverity? overrideSeverity, Guid actorId)
    {
        var result = SetStatus(DefectStatus.Triaged, actorId,
            $"Defect '{DefectNumber}' triaged; assigned to user {assignedToUserId}.");
        if (result.IsFailure) return result;

        AssignedToUserId = assignedToUserId;
        if (overrideSeverity.HasValue) Severity = overrideSeverity.Value;

        return DomainResult.Ok();
    }

    /// <summary>Moves the defect from Triaged to Open (accepted into maintenance backlog).</summary>
    public DomainResult Accept(Guid actorId) =>
        SetStatus(DefectStatus.Open, actorId,
            $"Defect '{DefectNumber}' accepted into maintenance backlog.");

    /// <summary>
    /// Defers the defect under MEL/CDL authority.
    /// Creates and links the DeferredDefect and MelReference records internally.
    /// </summary>
    public DomainResult Defer(
        DateTimeOffset deferredFrom,
        DateTimeOffset deferredUntil,
        Guid approvedByUserId,
        Guid signedByUserId,
        string melItemNumber,
        string melRevision,
        DeferralCategory deferralCategory,
        Guid actorId,
        int? operatorIntervalDays = null,
        string? logReference = null,
        Guid? stationId = null,
        string? operationalLimitations = null,
        string? maintenanceProcedures = null)
    {
        if (ActiveDeferral is not null)
            return DomainResult.Failure(
                "This defect already has an active deferral. Revoke it before creating a new one.");

        DeferredDefect deferral;
        try
        {
            deferral = DeferredDefect.Create(
                Id, deferredFrom, deferredUntil,
                approvedByUserId, signedByUserId,
                OrganisationId, actorId, logReference, stationId);
        }
        catch (ArgumentException ex)
        {
            return DomainResult.Failure(ex.Message);
        }

        MelReference melRef;
        try
        {
            melRef = MelReference.Create(
                deferral.Id, melItemNumber, melRevision,
                deferralCategory, OrganisationId, actorId,
                operatorIntervalDays, operationalLimitations, maintenanceProcedures);
        }
        catch (ArgumentException ex)
        {
            return DomainResult.Failure(ex.Message);
        }

        // Validate the deferral period does not exceed the MEL maximum
        var maxDays = melRef.MaxDeferralDays;
        var requestedDays = (deferredUntil - deferredFrom).TotalDays;
        if (requestedDays > maxDays)
            return DomainResult.Failure(
                $"Requested deferral of {requestedDays:F0} days exceeds MEL {melRef.Category} maximum of {maxDays} days.");

        deferral.AttachMelReference(melRef);

        var result = SetStatus(DefectStatus.Deferred, actorId,
            $"Defect '{DefectNumber}' deferred under MEL item {melItemNumber} until {deferredUntil:yyyy-MM-dd}.");
        if (result.IsFailure) return result;

        _deferrals.Add(deferral);

        RaiseDomainEvent(new DefectDeferredEvent
        {
            ActorId = actorId,
            OrganisationId = OrganisationId,
            EntityType = nameof(Defect),
            EntityId = Id,
            EventType = ComplianceEventType.RecordUpdated,
            DefectNumber = DefectNumber,
            DeferredDefectId = deferral.Id,
            Category = deferralCategory,
            DeferredUntil = deferredUntil,
            Description = $"Defect '{DefectNumber}' deferred (MEL {deferralCategory}, item {melItemNumber}) until {deferredUntil:yyyy-MM-dd}.",
        });

        return DomainResult.Ok();
    }

    /// <summary>
    /// Revokes the active deferral and returns the defect to Open.
    /// Called when a deferral expires or is manually cancelled.
    /// </summary>
    public DomainResult RevokeDeferral(string reason, Guid revokedByUserId, Guid actorId)
    {
        if (ActiveDeferral is null)
            return DomainResult.Failure("No active deferral to revoke.");

        ActiveDeferral.Revoke(reason, revokedByUserId, actorId);

        return SetStatus(DefectStatus.Open, actorId,
            $"Deferral for defect '{DefectNumber}' revoked: {reason}.");
    }

    /// <summary>Records that rectification work has started.</summary>
    public DomainResult StartRectification(Guid workOrderId, Guid actorId)
    {
        if (Status == DefectStatus.Deferred)
        {
            // Auto-revoke active deferral when work begins
            ActiveDeferral?.Revoke("Rectification commenced.", actorId, actorId);
        }

        var result = SetStatus(DefectStatus.RectificationInProgress, actorId,
            $"Defect '{DefectNumber}' rectification started under work order {workOrderId}.");
        if (result.IsFailure) return result;

        WorkOrderId = workOrderId;
        return DomainResult.Ok();
    }

    /// <summary>Logs a maintenance action against this defect.</summary>
    public DomainResult RecordAction(
        ActionType actionType,
        string description,
        Guid performedByUserId,
        DateTimeOffset performedAt,
        Guid actorId,
        string? ataReference = null,
        string? partNumber = null,
        string? serialNumber = null,
        Guid? workOrderId = null)
    {
        if (Status is DefectStatus.Cleared or DefectStatus.Closed)
            return DomainResult.Failure(
                $"Cannot record actions against a '{Status}' defect.");

        var action = DefectAction.Create(
            Id, actionType, description, performedByUserId, performedAt,
            OrganisationId, actorId, ataReference, partNumber, serialNumber, workOrderId);

        _actions.Add(action);
        UpdatedBy = actorId;
        UpdatedAt = DateTimeOffset.UtcNow;

        return DomainResult.Ok();
    }

    /// <summary>Marks rectification complete; awaiting independent inspection.</summary>
    public DomainResult SubmitForInspection(Guid actorId) =>
        SetStatus(DefectStatus.InspectionPending, actorId,
            $"Defect '{DefectNumber}' submitted for independent inspection.");

    /// <summary>
    /// Certifies the defect as cleared (issues CRS).
    /// Requires a <see cref="ActionType.CrsSignOff"/> action to have been recorded first.
    /// </summary>
    public DomainResult Clear(Guid certifyingStaffUserId, Guid actorId)
    {
        var hasCrs = _actions.Any(a => a.ActionType == ActionType.CrsSignOff
                                    && a.PerformedByUserId == certifyingStaffUserId);
        if (!hasCrs)
            return DomainResult.Failure(
                "A CRS sign-off action by the certifying staff member must be recorded before clearing.");

        var result = SetStatus(DefectStatus.Cleared, actorId,
            $"Defect '{DefectNumber}' cleared; CRS signed by user {certifyingStaffUserId}.");
        if (result.IsFailure) return result;

        RaiseDomainEvent(new DefectClearedEvent
        {
            ActorId = actorId,
            OrganisationId = OrganisationId,
            EntityType = nameof(Defect),
            EntityId = Id,
            EventType = ComplianceEventType.ReleaseSigned,
            DefectNumber = DefectNumber,
            AircraftId = AircraftId,
            CertifyingStaffUserId = certifyingStaffUserId,
            Description = $"Defect '{DefectNumber}' cleared by certifying staff (user {certifyingStaffUserId}).",
        });

        return DomainResult.Ok();
    }

    /// <summary>
    /// Closes the defect without rectification (no-fault-found, design feature, or admin close).
    /// <summary>
    /// Updates free-text fields while the defect is still in a mutable state.
    /// Only permitted in Reported or Open status.
    /// </summary>
    public DomainResult UpdateDetails(
        string? description,
        string? ataChapter,
        DefectSeverity? severity,
        Guid actorId)
    {
        if (Status is not (DefectStatus.Reported or DefectStatus.Open))
            return DomainResult.Failure(
                $"Defect details can only be updated in Reported or Open status. Current: {Status}.");

        if (description is not null)
            Description = description.Trim();
        if (ataChapter is not null)
            AtaChapter = ataChapter.Trim();
        if (severity.HasValue)
            Severity = severity.Value;

        UpdatedBy = actorId;
        UpdatedAt = DateTimeOffset.UtcNow;
        return DomainResult.Ok();
    }

    /// AD-mandated defects cannot be closed this way (HS-008) — they must be Cleared.
    /// </summary>
    public DomainResult Close(string reason, Guid actorId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(reason);

        if (IsAdMandated && Status != DefectStatus.Cleared)
            return DomainResult.Failure(
                "AD-mandated defects must be Cleared (CRS signed) before they can be Closed. " +
                "Direct closure without rectification is prohibited (HS-008).");

        var result = SetStatus(DefectStatus.Closed, actorId,
            $"Defect '{DefectNumber}' closed: {reason}.");
        if (result.IsFailure) return result;

        ClosureReason = reason.Trim();
        return DomainResult.Ok();
    }
}
